#!/bin/sh

	opt=$(echo "Reconnect\nConnect\nAdd " | dmenu -i -p "select wifi :- " -l 2 | cut -b 1)
case "$opt" in
	 A)
bssid=$(nmcli device wifi list | sed -n '1!p' | cut -b 9- | dmenu -i -p "select wifi :- " -l 10 | cut -d' ' -f1) || exit
pass=$(echo "" | dmenu -p "enter password:- ")
nmcli device wifi connect "$bssid" password "$pass" && notify-send ok || notify-send "not ok";;
	C) 
bssid=$(nmcli device wifi | sed -n '1!p' | cut -b 9- | dmenu -i -p "select wifi :- " -l 10 | cut -d' ' -f1)
nmcli device wifi connect "$bssid" && notify-send ok || notify-send "not ok";;
	R) 
bssid=$(nmcli device wifi | grep '*' | tr -s " "  | cut -d " " -f 2)
notify-send "$bssid"
nmcli device wifi connect "$bssid" && notify-send ok || notify-send "not ok";;
 	*)
notify-send 'a=add,c=connect'
;;
esac

